// Code generated by options-gen v0.55.5. DO NOT EDIT.

package logging

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithLevel(opt string) OptOptionsSetter {
	return func(o *Options) { o.level = opt }
}

func WithJson(opt bool) OptOptionsSetter {
	return func(o *Options) { o.json = opt }
}

func (o *Options) Validate() error {
	return nil
}
